tasks:
  - name: Install profiles dependencies
    command: |
      (cd /workspace && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3)
      chmod +x /workspace/get_helm.sh
      /workspace/get_helm.sh
      echo "deb http://ftp.de.debian.org/debian bullseye main " | sudo tee -a /etc/apt/sources.list
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 605C66F00D6C9793
      sudo apt-get update
      sudo apt-get install -y skopeo
      pip3 install yq
      exit